--liquibase formatted sql

--changeset app:001-create-users
CREATE TABLE users (
id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
username VARCHAR(50)  NOT NULL,
password VARCHAR(100) NOT NULL,
role     VARCHAR(20)  NOT NULL,
CONSTRAINT pk_users PRIMARY KEY (id),
CONSTRAINT uq_users_username UNIQUE (username)
);
--rollback DROP TABLE users;

--changeset app:002-create-notes
CREATE TABLE notes (
id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
title   VARCHAR(255)  NOT NULL,
content VARCHAR(4000) NOT NULL,
user_id BIGINT        NOT NULL,
CONSTRAINT pk_notes PRIMARY KEY (id),
CONSTRAINT fk_notes_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_notes_user_id ON notes (user_id);
--rollback DROP TABLE notes;
